# Generated by Django 4.2.2 on 2023-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_contact_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='furniture_complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('reason', models.TextField()),
                ('damage', models.TextField()),
            ],
        ),
    ]
